services:
  angie:
    image: docker.angie.software/angie:latest
    container_name: angie
    network_mode: host
    volumes:
      - ./angie.conf:/etc/angie/angie.conf
      - ./options-ssl-angie.conf:/etc/angie/options-ssl-angie.conf
      - 3x-ui-aio-volume:/var/lib/angie/acme/
    restart: unless-stopped

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    network_mode: host
    volumes:
      - 3x-ui-aio-volume:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "false"
    tty: true
    restart: unless-stopped

  authorization-stub:
    image: ampetelin/authorization-stub:latest
    container_name: authorization-stub
    network_mode: host
    restart: unless-stopped

volumes:
  3x-ui-aio-volume:
    name: 3x-ui-aio-volume
